//
//  HomeInteractor.swift
//  WeatherApplication
//
//  Created by Erkut Bas on 31.10.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class HomeInteractor {
    
    private let operationManager: HomeOperationProtocol
    
    init(operationManager: HomeOperationProtocol) {
        self.operationManager = operationManager
    }
    
}

// MARK: - Extensions -
extension HomeInteractor: HomeInteractorInterface {
    
    func getData(with completion: @escaping CharacterDataBlock) {
        operationManager.getData(with: completion)
    }
    
}
