//
//  HomeFormatter.swift
//  WeatherApplication
//
//  Created by Erkut Bas on 31.10.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class HomeFormatter {
    
    private var list: [CharacterData] = [CharacterData]()
    
}

// MARK: - Extensions -

extension HomeFormatter: HomeFormatterInterface {
    
    func setData(via response: CharacterDataResponse) {
        list = response.data.results
    }
    
    func askData(at index: Int) -> GenericDataProtocol? {
        return ContentDisplayerViewData(imageData: CustomImageViewComponentData(imageUrl: list[index].thumbnail.returnImageData()), name: list[index].name)
    }
    
    func askNumberOfSection() -> Int {
        return 0
    }
    
    func askNumberOfItem(in section: Int) -> Int {
        return list.count
    }
    
    func getItemId(at index: Int) -> ItemDetailViewRequest {
        return ItemDetailViewRequest(id: list[index].id, type: .present)
    }
    
}
