//
//  HomeViewController.swift
//  WeatherApplication
//
//  Created by Erkut Bas on 31.10.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class HomeViewController: UIViewController {
    
    // MARK: - Private properties -
    private var mainComponent: ItemCollectionView!
    
    // MARK: - Public properties -
    var presenter: HomePresenterInterface!

    // MARK: - Lifecycle -
    override func viewDidLoad() {
        super.viewDidLoad()
        
        view.backgroundColor = .white
        
        addMainComponent()
        
        presenter.viewDidLoad()
        
    }
    
    private func addMainComponent() {
        mainComponent = ItemCollectionView()
        mainComponent.translatesAutoresizingMaskIntoConstraints = false
        mainComponent.delegate = presenter
        
        view.addSubview(mainComponent)
        
        NSLayoutConstraint.activate([
        
            mainComponent.leadingAnchor.constraint(equalTo: view.leadingAnchor),
            mainComponent.trailingAnchor.constraint(equalTo: view.trailingAnchor),
            mainComponent.topAnchor.constraint(equalTo: view.topAnchor),
            mainComponent.bottomAnchor.constraint(equalTo: view.bottomAnchor),
        
        ])
    }
    
}

// MARK: - Extensions -
extension HomeViewController: HomeViewInterface {
    
    func refreshView() {
        DispatchQueue.main.async {
            self.mainComponent.reloadCollectionView()
        }
    }
    
}
