//
//  HomeWireframe.swift
//  WeatherApplication
//
//  Created by Erkut Bas on 31.10.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class HomeWireframe: BaseWireframe<HomeViewController> {

    // MARK: - Private properties -

    // MARK: - Module setup -

    init() {
        
        let moduleViewController = HomeViewController()
        moduleViewController.title = "Main"
        moduleViewController.tabBarItem.image = TabBarImages.home.value
        moduleViewController.tabBarItem.selectedImage = TabBarImages.homeSelected.value
        moduleViewController.navigationController?.setNavigationBarHidden(false, animated: false)

        super.init(viewController: moduleViewController)

        let formatter = HomeFormatter()
        let accessProviderManager = AccessProviderManager.shared
        let operationManager = HomeOperationManager(accessProviderManager: accessProviderManager)
        let interactor = HomeInteractor(operationManager: operationManager)
        let presenter = HomePresenter(view: moduleViewController, formatter: formatter, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }
    
    private func fireDetailView(with data: ItemDetailViewRequest) {
        
        let viewController = ItemDetailViewBuilder.build(with: data)
        
        switch data.type {
        case .push:
            navigationController?.pushViewController(viewController, animated: true)
        case .present:
            navigationController?.present(viewController, animated: true, completion: nil)
        }
        
    }

}

// MARK: - Extensions -
extension HomeWireframe: HomeWireframeInterface {
    
    func goToDetailView(with data: ItemDetailViewRequest) {
        print("geldik")
        fireDetailView(with: data)
    }
    
}
